version: '3'

services:
  db:
    image: postgres
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=pass
    restart: always

  app:
    build: 
      context: ./backend
    depends_on: 
      - db
    ports:
      - 8081:8080
    command: python3 main.py

  