version: '3'

services:
  db:
    image: postgres:11-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: app
      POSTGRES_PASSWORD: pass
    restart: always
    # container_name: docker_postgres
  app:
    build: 
      context: ./backend
    depends_on: 
      - db
    ports:
      - 8080:8080
    # command: python3 main.py
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload 
    container_name: docker_app
    tty: true

  